{% set name = "jquery-ui" %}
{% set version = "1.13.1" %}
{% set sha256 = "a14afc7bb990ee0d83f9f33fb5543c40d4a7e43ccbba144fbc8a14a64a1cffab" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jquery/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs

test:
  commands:
    - npm list -g jquery-ui
  requires:
    - nodejs


about:
  home: https://github.com/jquery/jquery-ui
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: The official jQuery user interface library.
  description: |
    jQuery UI is a curated set of user interface interactions, effects, widgets, 
    and themes built on top of jQuery. Whether you're building highly interactive 
    web applications, or you just need to add a date picker to a form control, 
    jQuery UI is the perfect choice. 
  doc_url: https://api.jqueryui.com/
  dev_url: https://github.com/jquery/jquery-ui

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
