{% set name = "jquery-ui" %}
{% set version = "1.13.2" %}
{% set sha256 = "7e5e539124c6e7f6cf07b9ef595438853603272b42cf40db5ed30650e94346cc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jquery/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs

test:
  commands:
    - npm list -g jquery-ui
  requires:
    - nodejs


about:
  home: https://github.com/jquery/jquery-ui
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: The official jQuery user interface library.
  description: |
    jQuery UI is a curated set of user interface interactions, effects, widgets, 
    and themes built on top of jQuery. Whether you're building highly interactive 
    web applications, or you just need to add a date picker to a form control, 
    jQuery UI is the perfect choice. 
  doc_url: https://api.jqueryui.com/
  dev_url: https://github.com/jquery/jquery-ui

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
