travis:
  secure:
    BINSTAR_TOKEN: NXZ0eKjZay9pNzf3Y0hP0GELuYfnC/cTt4jRez7kVpuHw2bmYL/INSv1+qp4sfY4PU+3fWJ9fph9Ki/Xkh5+lxD7rYGSLmuk30iO7UkRBCrUhzrSevODC3nZLtzc4FdZC6437psBHl9vosnnKM3MXVVj/hCZbO9y1n4+ME8kbqnpMn/65Thbo91GDIJfqJ4a19kDERoVetDelN7TSaoqVnHN6DePTHehnDH9l95i6XzEo9uDD9egt6DK5KxeAJnQ2UGf0uUbK26mPL2vhk3YxTizwmkOk2HKc9l2G05MCHNl/Fu6gBU2Zk4pnh729V7zVcspfAwHpWZ7gcSgqjXK9U5tZ1OP9pGF9V5+0AQvn1vxhYcGYfwqiPa4lh1ke2hv+0g3uHv4rTxMlJ15DBzUpwCCCn72rgSN7HG39vP0M08snCjJPeEZ47dhPAPB56eGaL/jYnvH4Z5OpPPE86lukyM47CWx+mx88Jaw+AS05Lrr/JiGhw0TdfbXYyiLuDkKYeDvJ7Fjv6Bo9fiG7ikTMRCakZTPNw3S1Bxl41wLjBzE1oUr1yL2yDDZaUZ7uZDymxtSO5FYc7ecLFm7h3q3JxtRZWPS6xMgA3jfyu3tlIii2QEeMP4YTmea2wff3qbc5iGzmkGc9dFmJbBBJX2IMohWSIg+EH/c9iiXYntgcns=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
