travis:
  secure:
    BINSTAR_TOKEN: XuecnzW7NBA4+RjJiMS5wSa/RVfb428mgVNOysvc2NWAJs25JL4zzOqmPvD64/BrAG2f3OzCJvXj6BvM7Xs5dzGdj+Mln9eFtIU84wTCxX4vVoNnqq2Qe/L8J3a+vU7OnrP5Aca35RxczTs524Rwbe78QhQr6NIDZXjIV1R/LeyKsnakmZzaJMJz750vJo6LUD2TI6pXsQfn+6Xgdy48Z1c4yzwc3C6vzneaRvC39GqZOWn5joqT5oZRRMoudCzGr4BK5vYZz2aLSZ+C4RSGZ/U7NyqZXCs7mgyVSIrhFC621yg3rm/FprdkGdChBJ1JiE2Yx5vWvNWbd+IMFyuVxvvB+npBXEbkItOJncbzN8+U4KuEQXHPtBMVxvHfHPazO/vUMchXXfzG5o4UsIeAvCn7zZs9K/M2rFByj9bSMUr0tznyNNgz8lG3v1u/sbAsSXZKKgu2YwCXJdLZXXzKPaWSj6wQXQRQFyjn3G2Ja3tcsFW6xGcMDABgNAK6GsBAluuHvqaSU8lnj7jlTH5oW2O2OqJ+9d6UXQehKyhODwNdW1/62E17pDrj7W3N2AFS/vnsKVoDwV1mSv9tHcJlM37TrNix3yB6WyDDmDe6q0jDUkYelUJ+SjHH7KHMeVTFzIF6QBcUF4uyEc1Rhl9UgRqo2Dgha2DvU7dD1zmdGFI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
